### ISSUE TITLE
will not run when told to in iOS

### ISSUE THREAD

**Issue by dishguy** [MortJC/homebridge-platform-orbit#34]
will not run when told to in iOS.... just hangs at waiting... or queued

**Comment by mishakim** [comment]
Same here. It worked the first few days I was using it, now it does not. I'm using three B-Hyve hose controllers, they all simply ignore what Home tells them to do (and Home state does not update when they are controlled from the B-Hyve app)

**Comment by dishguy** [comment]
Unfortunately  I cannot code so I can only point out what’s happening on my end and be grateful if something is released to address it

**Comment by MortJC** [comment]
Hi, Can you please run the hombridge in debug mode and send me the logs?

**Comment by mishakim** [comment]
It resumed working after I restarted to turn on debug mode (hadn't resumed working after a system restart yesterday). I have some plugins that are very verbose in debug mode, so I'll need to figure out a way to have only this plugin in debug, or run it in a dedicated homebridge instance in order to leave it running in debug long enough to reproduce the issue, and not just be swamped by the other plugins. But the log with it working is attached in case that helps.
[B-hyve log working.txt](https://github.com/MortJC/homebridge-platform-orbit/files/6632199/B-hyve.log.working.txt)

**Comment by MortJC** [comment]
Hi,

Unfortunately the working debug log won't help with debugging the issue.
